version: "3.9"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    depends_on:
      - db
      - redis
    env_file: .env
    stdin_open: true
    tty: true

  db:
    image: "postgres:alpine"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env
    expose:
      - "5432"
        
  redis:
    image: "redis:alpine"
    volumes:
      - redis-data:/data 
    env_file: .env 
      
  sidekiq:
    build: .
    depends_on:
      - app      
      - db
      - redis
    volumes:
      - .:/app
      - gem_cache:/usr/local/bundle/gems
    env_file: .env
    environment:
      RAILS_ENV: development
    entrypoint: ./entrypoints/sidekiq-entrypoint.sh    

volumes:
  db_data:
  redis-data:
  gem_cache: